### ISSUE TITLE
Update references to `source_config` and `target_config` in application manifests

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud.com#794]
Each reference to `source_config` and `target_config`, as well as the `target: <target>` structure are referring to deprecated fields in the Wadm application format. We should update each of these fields accordingly:

Source:
```yaml
source_config:
  - name: foo
```

to

```yaml
source:
  config:
    - name: foo
```

Target:
```yaml
target: footarget
target_config:
  - name: foo
```

to:

```yaml
target:
  name: footarget
  config:
    - name: foo
```
