### ISSUE TITLE
wasmcloud.toml reference docs out of sync

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wasmcloud.com#829]
No mention of `world` or `wit_world`:
https://wasmcloud.com/docs/reference/config/#type-config---component

But the top-level example for that page has:
```toml
name = "http-hello-world"
language = "rust"
type = "component"
version = "0.1.0"
[component]
wit_world = "hello"
wasm_target = "wasm32-wasi-preview2"
```
