### ISSUE TITLE
[FEAT] Clarify the difference (and use cases) between `wash dev` and `wash up`

### ISSUE THREAD

**Issue by joonas** [wasmCloud/wasmcloud.com#838]
[Comment in a recent hacker news thread](https://news.ycombinator.com/item?id=43039962) highlighted that it wasn't immediately clear from our existing documentation what the difference between `wash dev` and `wash up` is, and when you should prefer one over the other:

> It never really explains why I want `wash up` vs `wash dev`, where they differ, why they differ and why each exists. The `wash up` experience is much more clunky and, to be honest, I'd really just want to keep going with the same command that was working for me like `wash dev --dev` and then `wash dev --prod` with a heavy emphasis in the tutorial on the difference for each as it's really not clear.

If we have existing documentation that clarifies this, it seems like we may want to highlight that more, and if we do not have it captured, perhaps we should?

**Comment by NewMountain** [comment]
Just to follow up on this: my biggest pain point is that the docs imply `wash dev` means I can only run (and hot reload) a single component. I could easily see a use case where I want to spin up a few components (perhaps composed) on one or a few routes and the dev workflow of running `wash up` and then rebuilding every component seems like a sub-optimal dev experience.

**Comment by NewMountain** [comment]
For additional context, based on the docs [here](https://wasmcloud.com/docs/developer/components/run/), this is the only real example that appears to work for a multi-url example. From that I came up with this (gross but working) Makefile

```
.PHONY: deploy-components
deploy-components:
	cd /Users/newmountain/code/wasmtime_cloud/hello-go && wash build
	cd /Users/newmountain/code/wasmtime_cloud/hello-rust && wash build

	cd /Users/newmountain/code/wasmtime_cloud
	wash up -d

	# Deploy Go component
	wash start component file:///Users/newmountain/code/wasmtime_cloud/hello-go/build/hello-go_s.wasm hello-go
	wash start provider ghcr.io/wasmcloud/http-server:0.22.0 http-server-go
	# Create config and link
	wash config put hello-go-config address=0.0.0.0:8000
	wash link put http-server-go hello-go wasi http --source-config hello-go-config --interface incoming-handler

	# Deploy Rust component
	cd /Users/chris/code/wasmtime_cloud
	wash start component file:///Users/chris/code/wasmtime_cloud/hello-rust/build/http_hello_world_s.wasm hello-rust
	wash start provider ghcr.io/wasmcloud/http-server:0.22.0 http-server-rust
	# Create config and link
	wash config put hello-rust-config address=0.0.0.0:8002
	wash link put http-server-rust hello-rust wasi http --source-config hello-rust-config --interface incoming-handler
```

This is not anywhere near as polished as something like `wash dev`, but it does work. I'm sure I could wrap this in some sort of `fswatch` and more bash magic, but this already feels like it would be better handled `wash dev`

Based on the examples I found [here](https://wasmcloud.com/docs/developer/components/configure/) and [here](https://wasmcloud.com/docs/tour/deploy-and-scale/), my best guess for a project level `wadm.yaml` was

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: "wasmtime-cloud"
  annotations:
    description: "Multi-language WebAssembly Component Model demo using Go, and Rust"
spec:
  components:
    # Go Component
    - name: hello-go
      type: component
      properties:
        image: "file:///Users/newmountain/code/wasmtime_cloud/hello-go/build/hello-go_s.wasm"
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: httpserver-go
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.23.2
      traits:
        - type: link
          properties:
            target: hello-go
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 0.0.0.0:8000

    # Rust Component
    - name: hello-rust
      type: component
      properties:
        image: "file:///Users/newmountain/code/wasmtime_cloud/hello-rust/build/http_hello_world_s.wasm"
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: httpserver-rust
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.26.0
      traits:
        - type: link
          properties:
            target: hello-rust
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 0.0.0.0:8002
```

running either the command

`wash up --wadm-manifest project.wadm.yaml` or `wash up` seem to not work. Neither locahost:8000 or :8002 return a result (unable to connect) but there isn't really a useful log or error message.
